### ISSUE TITLE
Back end WS

### ISSUE THREAD

**Issue by Matthew-Dreemurr** [Blubby-42-Team/ft_transcendence#11]
## Todo

- [x] Choose WS vs Socket.io
- [ ] Game service logic @mkoyamba #13 
- [x] Auth guard with https://docs.nestjs.com/websockets/guards 
- [x] Pass auth JWT in the WS headers #38 
- [ ] Rework joinRoom #36 
- [ ] WS custom mode #39 
- [ ] WS classic mode #40 
- [ ] Check how to test ws
    -  https://socket.io/docs/v4/testing/

**Comment by Matthew-Dreemurr** [comment]
Using socket.io and setup basic dto error handling.

Need to do: 
- [ ] Auth guard with https://docs.nestjs.com/websockets/guards

**Comment by Matthew-Dreemurr** [comment]
First setup done with #16

**Comment by Matthew-Dreemurr** [comment]
Need to setup game logic service for @mkoyamba

**Comment by Matthew-Dreemurr** [comment]
Need to fix #36
