### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by Matthew-Dreemurr** [Blubby-42-Team/ft_transcendence#22]
## To-do

- [x] Generate our own unique ID for each user
- [x] Auth with 42
- [ ] GET /user/:id
    - [ ] coal
    - [ ] campus
    - [ ] pp
    - [ ] intra login
    - [ ] real name
    - [ ] intra display name -< intra login by default
    - [ ] campus country
    - [ ] pp url (by default, 42 cdn url)
- [ ] GET /user/:id/pp
    - [ ] img
