### ISSUE TITLE
rework joinRoom logic

### ISSUE THREAD

**Issue by Matthew-Dreemurr** [Blubby-42-Team/ft_transcendence#36]
## TODO
 - [x] User should be allowed to join a room only if he is in the white list 
 - [x] Only check if there is a client connected to the room 
     - [x] If it's the case, disconnect the old client and connect the new one 
- [x]  Join player WS
- [ ] ~~#43~~

https://github.com/Blubby-42-Team/ft_transcendence/blob/60a38236f3e7d0fd788bafc0c50543f279dae7c1/server/src/controller/game/game.gateway.ts#L39-L56
