### ISSUE TITLE
Shared lib

### ISSUE THREAD

**Issue by Matthew-Dreemurr** [Blubby-42-Team/ft_transcendence#6]
## Todo
- [x] Create shared lib for dto and ...
- [x] Setup tsconfig for nest
- [x] Setup tsconfig fort nuxt

Resources: 
https://github.com/modernweb-pl/vue-nest-monorepo
