### ISSUE TITLE
There must be a matchmaking system: the user can join a queue until they get automatically matched with someone else.

### ISSUE THREAD

**Issue by Matthew-Dreemurr** [Blubby-42-Team/ft_transcendence#65]
# Todo

- [x] https://github.com/Blubby-42-Team/ft_transcendence/commit/b8dc9eb16c079dd5d8423a7aeb02dd53cf268a50
    - [x] Manage user disconnection
        - [x] Remove player from all list
        - [ ] Stop game
        - [ ] Store game score
            - [ ] disconnect player, keep current score
            - [ ] the player left has max score

**Comment by Matthew-Dreemurr** [comment]
Need to make emit logic for front end event
@willaCS
